"""Criando campo senha na tabela pessoa

Revision ID: 133eecd174e2
Revises: 42f190acc411
Create Date: 2025-05-28 15:43:54.302534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '133eecd174e2'
down_revision: Union[str, None] = '42f190acc411'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'pessoa', 
        sa.Column('senha', 
        sa.String(length=50),
        nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pessoa', 'senha')
    # ### end Alembic commands ###
