"""tabela atualizada

Revision ID: 1595d1141aaf
Revises: b70bd5a4ae45
Create Date: 2025-05-29 15:03:53.749582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1595d1141aaf'
down_revision: Union[str, None] = 'b70bd5a4ae45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pessoa', sa.Column('nome', sa.String(length=50), nullable=False))
    op.drop_column('pessoa', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pessoa', sa.Column('name', sa.VARCHAR(length=50), nullable=False))
    op.drop_column('pessoa', 'nome')
    # ### end Alembic commands ###
